export const daosDictionary: Record<string, string> = {
  aave: 'aave',
  op: 'op',
  optimism: 'optimism',
  pooltogether: 'pooltogether',
  yamfinance: 'yamfinance',
  ssvnetwork: 'ssvnetwork',
  dydx: 'dydx',
  connext: 'connext',
  dimo: 'dimo',
  gitcoin: 'gitcoin',
  element: 'element',
  starknet: 'starknet',
  developerdao: 'developerdao',
  apecoin: 'apecoin',
  safe: 'safe',
  rocketpool: 'rocketpool',
  moonriver: 'moonriver',
  moonbeam: 'moonbeam',
  compound: 'compound',
  moonbase: 'moonbase',
  arbitrum: 'arbitrum',
};
