export const daosDictionary: Record<string, string> = {
  aave: 'aave',
  op: 'op',
  optimism: 'optimism',
  pooltogether: 'pooltogether',
  yamfinance: 'yamfinance',
  ssvnetwork: 'ssvnetwork',
  dydx: 'dydx',
  dimo: 'dimo',
  gitcoin: 'gitcoin',
  element: 'element',
  starknet: 'starknet',
  developerdao: 'developerdao',
  apecoin: 'apecoin',
  safe: 'safe',
};
